baseURL = "https://github.com/ishii-git/blogdown.git"
title = "ishii-blog"
languageCode = "ja-jp"
paginate = 10
theme = "Binario"
disqusShortname = "ishii-blog" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true
publishDir = "docs"
hasCJKLanguage = true


[Author] # Used in authorbox
  name = "ishii"

[Params]
  description = "Responsive card-based & code-light Hugo theme" # Site Description. Used in meta description
  copyright = "石井" # Copyright holder, otherwise will use .Site.Title
  columns = 2 # Set the number of cards columns. Possible values: 1, 2, 3
  mainSections = ["post"] # Set main page sections


[Params.Entry]
  meta = ["date", "categories"] # Enable meta fields in given order

[Params.Featured]
  previewOnly = false # Show only preview featured image

[Params.Breadcrumb]
  enable = true # Enable breadcrumb block globally
  homeText = "ishii-blog"# Home node text

